'''new = open('neeew.txt' ,'r')
print(new.read())
new.close()
new_2 = open('D:/project/newsss.txt','r')
print(new_2.read())
new_2.close()

new_3 = open('D:/project/newsss.txt' ,'r')
print(new_3.name)
print(new_3.mode)
new_4 = open('D:/project/newsss.txt' ,'r')
print(new_4.readline())
new_4.close()
new_5 = open('D:/project/newsss.txt' ,'r')
print(new_5.readlines())
new_5.close()
new_6 = open('D:/project/newsss.txt' ,'r')
print(new_6.readline())
print(new_6.read())
new_6.close()
new_7 = open('D:/project/newsss.txt' ,'r')
print(new_7.readline())
new_7.seek(0)
print(new_7.read())
new_7.close()'''
#w for write mode
new_8 = open('D:/project/newsss.txt' ,'w')
new_8.write('good morning')
new_8.close()
#a for append mode
new_9 = open('D:/project/newsss.txt' ,'a')
new_9.write('\nGood Evening')
new_9.close()
